#!/bin/bash -e

mkdir -p /var/muondetector
useradd muonuser -g users -G dialout,pi,i2c,users,gpio -s /usr/sbin/nologin -r -N -M -b /var/muondetector || adduser muonuser gpio
chown muonuser:users /var/muondetector
chmod g+w /var/muondetector
