#!/bin/bash
mkdir -p /var/muondetector
useradd muonuser -g users -G dialout,pi,i2c -s /usr/sbin/nologin -r -N -M -b /var/muondetector
chown -R muonuser:pi /var/muondetector
chmod -R g+w /var/muondetector
