#!/bin/bash
mkdir -p /var/muondetector
useradd muonuser -g pi -G users,dialout,i2c -s /usr/sbin/nologin -r -N -M -b /var/muondetector
chown -R muonuser:users /var/muondetector
chmod -R g+w /var/muondetector
