#ifndef MUONDETECTOR_SHARED_GLOBAL_H
#define MUONDETECTOR_SHARED_GLOBAL_H

#include <QtCore/qglobal.h>

#cmakedefine MUONDETECTOR_SHARED_LIBRARY

#ifdef MUONDETECTOR_SHARED_LIBRARY
#define MUONDETECTORSHARED Q_DECL_EXPORT
#else
#define MUONDETECTORSHARED Q_DECL_IMPORT
#endif

#endif // MUONDETECTOR_SHARED_GLOBAL_H
