components =
(
    {
        id = "ADC_DRIVER_0";
        device = "ADS1115_0";
        every = 1000; # ms
    },
    {
        id = "DAC_DRIVER_0";
        device = "MCP4728_0";
    },
    {
        id = "PCA9536_DRIVER_0";
        device = "PCA9536_0";
    },
    {
        id = "EEPROM_DRIVER_0";
        device = "EEPROM24AA02_0";
    },
    {
        id = "OLED_DRIVER_0";
        device = "ADAFRUIT_SSD1306_0";
    },
    {
        id = "GPIO_DRIVER_0";
    },
    {
        id = "GPS_DRIVER_0";
    },
    {
        id = "TEMP_SOURCE_0";
        device = "LM75_0";
        every = 5000; #ms
    },
    {
        id = "TEMP_SOURCE_1";
        device = "MIC184_0";
        every = 5000; #ms
    },
    {
        id = "TCP_SOURCE_0";
    },
    {
        id = "TCP_COMMAND_DECODER_0";
    },
    {
        id = "LOG_ENGINE_0";
        every = 5000; #ms log interval
    }
);
