components =
(
    {
        id = "ADC_DRIVER_0";
        device = "ADS1115_0";
        every = 1000; # ms
    },
    {
        id = "DAC_DRIVER_0";
        device = "MCP4728_0";
    },
    {
        id = "EEPROM_DRIVER_0";
        device = "EEPROM24AA02_0";
    },
    {
        id = "GPIO_DRIVER_0";
    },
    {
        id = "GPS_DRIVER_0";
    },
    {
        id = "TCP_SOURCE_0";
    }
);
