components =
(
    {
        id = "ADC_SOURCE_0";
        device = "ADS1115_0";
        every = 1000; # ms
    },
    {
        id = "GPS_SOURCE_0";
        device = "GPS_UART_0";
    },
    {
        id = "TCP_SOURCE_0";
    }
);
