devices =
(
    {
        id = "AD1115_0";
        type = "ADC";
        category = "i2c";
        address = 0x48;
        device = "/dev/i2c-1";
    },
    {
        id = "MCP4728_0";
        type = "DAC";
        category = "i2c";
        address = 0x60;
        device = "/dev/i2c-1";
    },
    {
        id = "EEPROM24AA02_0";
        type = "EEPROM";
        category = "i2c";
        address = 0x50;
        device = "/dev/i2c-1";
    }
);