devices =
(
    {
        id = "ADS1115_0";
        type = "ADC";
        category = "i2c";
        address = 0x48;
        device = "/dev/i2c-1";
    },
    {
        id = "MCP4728_0";
        type = "DAC";
        category = "i2c";
        address = 0x60;
        device = "/dev/i2c-1";
    },
    {
        id = "PCA9536_0";
        type = "IO_EXTENDER";
        category = "i2c";
        address = 0x41;
        device = "/dev/i2c-1";
    },
    {
        id = "EEPROM24AA02_0";
        type = "EEPROM";
        category = "i2c";
        address = 0x50;
        device = "/dev/i2c-1";
    },
    {
        id = "LM75_0";
        type = "TEMP";
        category = "i2c";
        address = 0x4f;
        device = "/dev/i2c-1";
    },
    {
        id = "MIC184_0";
        type = "TEMP";
        category = "i2c";
        address = 0x4f;
        device = "/dev/i2c-1";
    },
    {
        id = "UBLOX_I2C_0";
        type = "OTHER";
        category = "i2c";
        address = 0x42;
        device = "/dev/i2c-1";
    },
    {
        id = "ADAFRUIT_SSD1306_0";
        type = "DISPLAY";
        category = "i2c";
        address = 0x3c;
        device = "/dev/i2c-1";
    }
);