devices =
(
    {
        id = "AD1115";
        type = "ADC"
        category = "i2c";
        address = 0x48;
        device = "/dev/i2c-1";
    },
    {
        id = "GPS_UART";
        type = "OTHER"
        category = "uart";
        device = "/dev/ttyUSB0";
        baud = 115200;
    }
);