.\" Manpage for muondetector-login
.\" Contact developer@muonpi.org to correct errors or typos.
.TH "muondetector-login" "1" "@PROJECT_DATE_STRING@" "v @PROJECT_VERSION_MAJOR@.@PROJECT_VERSION_MINOR@.@PROJECT_VERSION_PATCH@" "muondetector login  manpage"
.SH NAME
muondetector-login \- manage stored MQTT credentials for muondetector-daemon
.SH SYNOPSIS
.B muondetector-login
\fBstore\fP|\fBget\fP|\fBclear\fP
.SH DESCRIPTION
.B muondetector-login
stores, retrieves or clears the MQTT credentials used by
.BR muondetector-daemon (1).
Credentials are written to
.IR /etc/muondetector/muondetector.conf
as
.B mqtt_user
and
.BR mqtt_password .
.SH OPTIONS
.TP
\fBstore\fP
Prompt for username and password, verify the MQTT connection and store the
credentials in the daemon configuration file. This usually requires root
permissions:
.PP
.EX
sudo muondetector-login store
.EE
.TP
\fBget\fP
Print the configured MQTT username and report whether a password is configured.
.TP
\fBclear\fP
Remove MQTT credential entries from the daemon configuration file. This usually
requires root permissions:
.PP
.EX
sudo muondetector-login clear
.EE
.SH SEE ALSO
.BR muondetector-daemon (1)
.SH BUGS
No known bugs.
.SH AUTHOR
MuonPi.org <developer@muonpi.org>
.SH COPYRIGHT
License: LGPL-3.0-or-later
.PP
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
.PP
This package is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.
.PP
You should have received a copy of the GNU Lesser General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
.PP
On Debian systems, the complete text of the GNU Lesser General
Public License version 3 can be found in "/usr/share/common-licenses/LGPL-3".
