.\" manpage for muondetector-daemon
.\" Contact developer@muonpi.org to correct errors or typos
.TH "muondetector-daemon" "1" "@PROJECT_DATE_STRING@" "v @PROJECT_VERSION_MAJOR@.@PROJECT_VERSION_MINOR@.@PROJECT_VERSION_PATCH@" "muondetector manpage"
.SH "NAME"
muondetector-daemon - daemon for muondetector board
.SH "SYNOPSIS"
.B muondetector-daemon
[\fIoptions\fP] [\fIgnss-device\fP]
.br
Starts the daemon.
.SH "DESCRIPTION"
.B muondetector-daemon
.
.br
The daemon is intended to run in the background and manage all communications
between the muondetector HAT and connected hardware. It reads GNSS data from a
u-blox receiver, communicates with hardware components via I2C and GPIO, accepts
TCP connections from the GUI, and can publish or store measurement data through
configured sinks.
.PP
Most defaults are read from the muondetector configuration files. Command line
options override the corresponding configuration values for the current run.
.SH "OPTIONS"
.TP
\fB-h, --help\fP
Displays a help page.
.TP
\fB-l, --logging\fP \fIlevel\fP
Set log verbosity. Supported values are \fBWarning\fP, \fBError\fP, \fBInfo\fP
and \fBDebug\fP.
.TP
\fB-b\fP \fIbaud\fP
Set the GNSS serial baud rate.
.TP
\fB-d\fP
Dump raw GNSS data.
.TP
\fB--showin, --showincoming\fP
Show incoming u-blox messages as hex.
.TP
\fB--showout, --showoutgoing\fP
Show outgoing u-blox messages as hex.
.TP
\fB--server, --daemonAddress\fP \fIaddress\fP
Set the IPv4 address the daemon listens on for GUI TCP connections.
.TP
\fB--dp, --daemonPort\fP \fIport\fP
Set the TCP port the daemon listens on for GUI connections.
.TP
\fB--th1, --discr1\fP \fIvoltage\fP
Set discriminator threshold voltage for channel 1.
.TP
\fB--th2, --discr2\fP \fIvoltage\fP
Set discriminator threshold voltage for channel 2.
.TP
\fB--bias\fP \fIvoltage\fP
Set SiPM bias output voltage.
.TP
\fB-p\fP
Enable SiPM bias voltage.
.TP
\fB--pre1\fP
Enable pre-amplifier 1.
.TP
\fB--pre2\fP
Enable pre-amplifier 2.
.TP
\fB-g, --gain\fP
Enable high gain.
.TP
\fB--pol1\fP \fI0|1\fP
Set input polarity for channel 1.
.TP
\fB--pol2\fP \fI0|1\fP
Set input polarity for channel 2.
.TP
\fB-t, --trigger\fP \fImode\fP
Set event trigger input:
.br
0 - XOR
.br
1 - AND
.br
2 - time measurement output
.br
3 - external trigger
.TP
\fB--id\fP \fIstation-id\fP
Set station ID for distinguishing multiple detectors owned by one user.
.TP
\fB--pca, --signal\fP \fImask\fP
Set the PCA port mask used for timing input selection.
.TP
\fB--sds011_n_sleep\fP \fIminutes\fP
Set the SDS011 sleep/readout interval parameter. The daemon uses this value to
schedule SDS011 particulate matter readout.
.TP
\fIgnss-device\fP
Optional positional path to the u-blox GNSS serial device, for example
\fI/dev/ttyAMA0\fP or \fI/dev/ttyUSB0\fP.
.SH "EXIT STATUS"
\fB0\fP on normal shutdown, non-zero on configuration or startup errors.
.SH "BUGS"
No known bugs.
.SH "AUTHOR"
MuonPi.org <developer@muonpi.org>
.SH "COPYRIGHT"
License: LGPL-3.0-or-later
.PP
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
.PP
This package is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.
.PP
You should have received a copy of the GNU Lesser General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
.PP
On Debian systems, the complete text of the GNU Lesser General
Public License version 3 can be found in "/usr/share/common-licenses/LGPL-3".
