#!/bin/bash -e
deb-systemd-helper stop muondetector-daemon.service
deb-systemd-helper stop pigpiod.service
deb-systemd-helper disable muondetector-daemon.service
deb-systemd-helper disable pigpiod.service
