sources =
(
    {
        id = "ADC_SOURCE";
        device = "AD1115";
        every = 1000; # ms
    },
    {
        id = "GPS_SOURCE";
        device = "GPS_UART";
        baudrate = 9600;
    },
    (
        id = "TCP_SOURCE";
        device = "TCP_CONNECTION"
    )
);