#!/bin/bash
ln -s /usr/lib/libmuondetector-shared.so.1.1.0 /usr/lib/libmuondetector-shared.so.1.1
ln -s /usr/lib/libmuondetector-shared.so.1.1 /usr/lib/libmuondetector-shared.so.1
ln -s /usr/lib/libmuondetector-shared.so.1 /usr/lib/libmuondetector-shared.so
