set(MUONDETECTOR_HARDWARE_SRC_DIR "${CMAKE_CURRENT_SOURCE_DIR}/daemon/src/hardware")
set(MUONDETECTOR_DAEMON_BINARY_DIR "${CMAKE_BINARY_DIR}/daemon")


set(MUONDETECTOR_I2C_SOURCE_FILES
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/Adafruit_GFX.cpp"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/adafruit_ssd1306.cpp"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/ads1115.cpp"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/bme280.cpp"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/bmp180.cpp"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/eeprom24aa02.cpp"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/hmc5883.cpp"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/lm75.cpp"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/mcp4728.cpp"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/pca9536.cpp"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/sht21.cpp"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/sht31.cpp"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/tca9546a.cpp"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/ubloxi2c.cpp"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/x9119.cpp"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/mic184.cpp"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/ltr390uv01.cpp"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/as7331.cpp"

    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/i2cdevice.cpp"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/i2cutil.cpp"

    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2cdevices.cpp"
    )

set(MUONDETECTOR_I2C_HEADER_FILES
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/Adafruit_GFX.h"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/adafruit_ssd1306.h"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/ads1015.h"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/ads1115.h"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/bme280.h"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/bmp180.h"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/eeprom24aa02.h"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/glcdfont.h"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/hmc5883.h"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/lm75.h"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/mcp4728.h"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/pca9536.h"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/sht21.h"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/sht31.h"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/tca9546a.h"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/ubloxi2c.h"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/x9119.h"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/mic184.h"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/ltr390uv01.h"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/as7331.h"

    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/i2cdevice.h"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2c/i2cutil.h"

    "${MUONDETECTOR_HARDWARE_SRC_DIR}/device_types.h"
    "${MUONDETECTOR_HARDWARE_SRC_DIR}/i2cdevices.h"
    )

add_library(muondetector-hardware STATIC
    ${MUONDETECTOR_I2C_SOURCE_FILES}
    ${MUONDETECTOR_I2C_HEADER_FILES}
)

target_include_directories(muondetector-hardware
    PUBLIC
        $<BUILD_INTERFACE:${MUONDETECTOR_HARDWARE_SRC_DIR}>
        $<INSTALL_INTERFACE:include>
)
