set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

message(STATUS "CMAKE_PREFIX_PATH" ${CMAKE_PREFIX_PATH})
message(STATUS "Qt6_DIR" ${Qt6_DIR})
message(STATUS "Qt6Core_DIR" ${Qt6Core_DIR})

set(CMAKE_C_COMPILER arm-linux-gnueabihf-gcc)
set(CMAKE_CXX_COMPILER arm-linux-gnueabihf-g++)

set(SYSROOT $ENV{HOME}/actions-runner/sysroot)

set(CMAKE_FIND_ROOT_PATH
    ${SYSROOT}
    ${SYSROOT}/usr/lib/arm-linux-gnueabihf
)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)