name: CI

on:
  push:
  pull_request:

jobs:
  build-x64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build build-essential \
           qt6-base-dev qt6-svg-dev qt6-declarative-dev qt6-positioning-dev \
           libboost-all-dev \
           libcapnp-dev capnproto libglib2.0-dev libsecret-1-dev

      - name: Configure
        run: cmake -S . -B build-x64 \
                -DMUONDETECTOR_BUILD_DAEMON=OFF \
                -DMUONDETECTOR_BUILD_TESTS=OFF \
                -DMUONDETECTOR_BUILD_TCP_DEBUG_CLIENT=OFF \
                -DMUONDETECTOR_BUILD_TCP_DEBUG_SERVER=OFF \
                -DCMAKE_BUILD_TYPE=Release \
                -G Ninja

      - name: Build
        run: cmake --build build-x64

      - name: Package .deb
        run: |
          cd build-x64
          cpack -G DEB

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-x64
          path: build-x64/*.deb


  build-armv7:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install cross tools
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

      - name: Configure
        run: |
          cmake -S . -B build-armhf \
            -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain-armv7.cmake \
            -DCMAKE_SYSROOT=$HOME/actions-runner/sysroot \
            -DCMAKE_BUILD_TYPE=Release \
            -G Ninja

      - name: Build
        run: cmake --build build-armhf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-armhf
          path: build-armhf/*.deb

  # build-arm64:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Install cross tools
  #       run: |
  #         sudo apt update
  #         sudo apt install -y cmake ninja-build gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

  #     - name: Configure
  #       run: |
  #         cmake -S . -B build \
  #           -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain-arm64.cmake \
  #           -G Ninja

  #     - name: Build
  #       run: cmake --build build