name: CI

on:
  push:
  pull_request:

jobs:
  build-x64:
    runs-on: [self-hosted, X64, Linux, x64-build]

    steps:
      - uses: actions/checkout@v4

      # - name: Install deps
      #   run: |
      #     sudo apt update
      #     sudo apt install -y cmake ninja-build build-essential \
      #      qt6-base-dev qt6-svg-dev qt6-declarative-dev qt6-positioning-dev \
      #      libboost-all-dev \
      #      libcapnp-dev capnproto libglib2.0-dev libsecret-1-dev libconfig-dev

      - name: Configure
        run: |
          cmake -S . \
                -DMUONDETECTOR_BUILD_DAEMON=OFF \
                -DMUONDETECTOR_BUILD_TESTS=OFF \
                -DMUONDETECTOR_BUILD_TCP_DEBUG_CLIENT=OFF \
                -DMUONDETECTOR_BUILD_TCP_DEBUG_SERVER=OFF \
                -DCMAKE_BUILD_TYPE=Release \
                -G Ninja

      - name: Build
        run: cmake --build . --parallel $(nproc)

      - name: Package .deb
        run: cpack -G DEB

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-x64
          path: ./*.deb


  build-armv7:
    runs-on: [self-hosted, Linux, X64, armhf-build]

    steps:
      - uses: actions/checkout@v4

      # - name: Install cross tools
      #   run: |
      #     sudo apt update
      #     sudo apt install -y cmake ninja-build gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

      - name: Debug sysroot
        run: |
          echo "SYSROOT=$SYSROOT"
          ls -lah $HOME/actions-runner/sysroot || true
          ls -lah /var/armhf/sysroot || true

      - name: Configure
        run: |
          echo $HOME/actions-runner/sysroot
          cmake -S . \
            -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain-armv7.cmake \
            -DCMAKE_SYSROOT=/var/armhf/sysroot \
            -DCapnProto_DIR=/var/armhf/sysroot/usr/lib/arm-linux-gnueabihf/cmake/CapnProto \
            -DCMAKE_BUILD_TYPE=Release \
            -G Ninja

      - name: Build
        run: cmake --build . --parallel $(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-armhf
          path: ./*.deb

  build-win32:
    runs-on: [self-hosted, Windows, X64, win32-build]

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        shell: pwsh
        run: |
          C:\Qt\6.11.1\llvm-mingw_64\bin\qt-cmake.bat `
          -G "Ninja" `
          -DCMAKE_MAKE_PROGRAM="C:/Qt/Tools/Ninja/ninja.exe" `
          -DCMAKE_CXX_COMPILER="C:/Qt/Tools/llvm-mingw1706_64/bin/clang++.exe" `
          -DBoost_INCLUDE_DIRS="C:/boost-1.91.0/libs" `
          -DMUONDETECTOR_BUILD_DAEMON=OFF `
          -DMUONDETECTOR_BUILD_TESTS=OFF `
          -DMUONDETECTOR_BUILD_TCP_DEBUG_CLIENT=OFF `
          -DMUONDETECTOR_BUILD_TCP_DEBUG_SERVER=OFF `
          .
  # build-arm64:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Install cross tools
  #       run: |
  #         sudo apt update
  #         sudo apt install -y cmake ninja-build gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

  #     - name: Configure
  #       run: |
  #         cmake -S . -B build \
  #           -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain-arm64.cmake \
  #           -G Ninja

  #     - name: Build
  #       run: cmake --build build